#!/bin/bash

cd sources
npm install

case "$1" in
    all)
        nprm run all
        ;;
    act)
        # Build and copy outputs to the dist directory
        npm run build
        cd ..
        cp -r sources/dist .
        # Run act
        $@
        # Revert the changes to the dist directory
        git co -- dist
        ;;
    *)
        npm run build
        ;;
esac