#!/bin/bash

cd sources

case "$1" in
    all)
        npm clean-install
        npm run all
        ;;
    act)
        # Build and copy outputs to the dist directory
        npm install
        npm run build
        cd ..
        cp -r sources/dist .
        # Run act
        $@
        # Revert the changes to the dist directory
        git checkout -- dist
        ;;
    init-scripts)
        cd test/init-scripts
        ./gradlew check
        ;;
    dist)
        npm install
        npm run build
        cd ..
        cp -r sources/dist .
        ;;
    *)
        npm install
        npm run build
        ;;
esac
