name: 'Build and upload distribution'
# Builds the action distribution an uploads as an artifact for later download
runs:
  using: "composite"
  steps: 
    - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
      with:
        node-version: 20
        cache: npm
        cache-dependency-path: sources/package-lock.json
    - name: Build distribution
      shell: bash
      run: |
        npm -v
        node -v
        npm install
        npm run build
      working-directory: sources

    - name: Copy the generated sources/dist directory to the top-level dist
      shell: bash
      run: |
        cp -r sources/dist .

    - name: Upload distribution
      uses: actions/upload-artifact@6f51ac03b9356f520e9adb1b1b7802705f340c2b # v4.5.0
      with:
        name: dist
        path: dist/
