name: 'Build and upload distribution'
# Builds the action distribution an uploads as an artifact for later download
runs:
  using: "composite"
  steps: 
    - uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
      with:
        node-version: 20
        cache: npm
        cache-dependency-path: sources/package-lock.json
    - name: Build distribution
      shell: bash
      run: |
        npm -v
        node -v
        npm install
        npm run build
      working-directory: sources

    - name: Copy the generated sources/dist directory to the top-level dist
      shell: bash
      run: |
        cp -r sources/dist .

    - name: Upload distribution
      uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # v4.6.1
      with:
        name: dist
        path: dist/
