name: 'Initialize integ-test'

runs:
  using: "composite"
  steps: 
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 11

    # Downloads a 'dist' directory artifact that was uploaded in an earlier 'build-dist' step
    - name: Download dist
      uses: actions/download-artifact@v4
      with:
        name: dist
        path: dist/
