name: CI-full-check

on:
  workflow_dispatch:
  push:
    branches: 
      - main
      - release/**
  pull_request:
    types: [assigned]

jobs:
  build-distribution:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v4
    - name: Build and upload distribution
      uses: ./.github/actions/build-dist

  action-inputs:
    needs: build-distribution
    uses: ./.github/workflows/integ-test-action-inputs.yml
    with:
      cache-key-prefix: ${{github.run_number}}-

  cache-cleanup:
    needs: build-distribution
    uses: ./.github/workflows/integ-test-cache-cleanup.yml
    with:
      cache-key-prefix: ${{github.run_number}}-

  caching-config:
    needs: build-distribution
    uses: ./.github/workflows/integ-test-caching-config.yml
    with:
      cache-key-prefix: ${{github.run_number}}-

  dependency-graph:
    needs: build-distribution
    uses: ./.github/workflows/integ-test-dependency-graph.yml
    permissions:
      contents: write
    with:
      cache-key-prefix: ${{github.run_number}}-

  dependency-submission:
    needs: build-distribution
    uses: ./.github/workflows/integ-test-dependency-submission.yml
    permissions:
      contents: write
    with:
      cache-key-prefix: ${{github.run_number}}-

  dependency-submission-failures:
    needs: build-distribution
    uses: ./.github/workflows/integ-test-dependency-submission-failures.yml
    with:
      cache-key-prefix: ${{github.run_number}}-

  execution-with-caching:
    needs: build-distribution
    uses: ./.github/workflows/integ-test-execution-with-caching.yml
    with:
      cache-key-prefix: ${{github.run_number}}-

  execution:
    needs: build-distribution
    uses: ./.github/workflows/integ-test-execution.yml
    with:
      cache-key-prefix: ${{github.run_number}}-

  develocity-injection:
    needs: build-distribution
    uses: ./.github/workflows/integ-test-inject-develocity.yml
    with:
      cache-key-prefix: ${{github.run_number}}-
    secrets:
      DEVELOCITY_ACCESS_KEY: ${{ secrets.GE_SOLUTIONS_ACCESS_TOKEN }}

  provision-gradle-versions:
    needs: build-distribution
    uses: ./.github/workflows/integ-test-provision-gradle-versions.yml
    with:
      cache-key-prefix: ${{github.run_number}}-

  restore-configuration-cache:
    needs: build-distribution
    uses: ./.github/workflows/integ-test-restore-configuration-cache.yml
    with:
      cache-key-prefix: ${{github.run_number}}-
    secrets:
      GRADLE_ENCRYPTION_KEY: ${{ secrets.GRADLE_ENCRYPTION_KEY }}

  restore-custom-gradle-home:
    needs: build-distribution
    uses: ./.github/workflows/integ-test-restore-custom-gradle-home.yml
    with:
      cache-key-prefix: ${{github.run_number}}-

  restore-containerized-gradle-home:
    needs: build-distribution
    uses: ./.github/workflows/integ-test-restore-containerized-gradle-home.yml
    with:
      cache-key-prefix: ${{github.run_number}}-

  restore-gradle-home:
    needs: build-distribution
    uses: ./.github/workflows/integ-test-restore-gradle-home.yml
    with:
      cache-key-prefix: ${{github.run_number}}-

  restore-java-toolchain:
    needs: build-distribution
    uses: ./.github/workflows/integ-test-restore-java-toolchain.yml
    with:
      cache-key-prefix: ${{github.run_number}}-

  sample-kotlin-dsl:
    needs: build-distribution
    uses: ./.github/workflows/integ-test-sample-kotlin-dsl.yml
    with:
      cache-key-prefix: ${{github.run_number}}-

  sample-gradle-plugin:
    needs: build-distribution
    uses: ./.github/workflows/integ-test-sample-gradle-plugin.yml
    with:
      cache-key-prefix: ${{github.run_number}}-

  toolchain-detection:
    needs: build-distribution
    uses: ./.github/workflows/integ-test-detect-java-toolchains.yml
    with:
      cache-key-prefix: ${{github.run_number}}-
