name: CI-integ-test-full

on:
  workflow_dispatch:
  push:
    branches:
    - 'main'
    - 'bot/gradle-actions-caching'
    paths:
    - 'dist/**'
    - 'sources/vendor/gradle-actions-caching/**'

permissions:
  contents: read

jobs:
  caching-integ-tests:
    uses: ./.github/workflows/suite-integ-test-caching.yml
    concurrency:
      group: CI-integ-test-caching
      cancel-in-progress: false
    with:
      skip-dist: true
    secrets: inherit

  other-integ-tests:
    permissions:
      contents: write
    needs: caching-integ-tests
    uses: ./.github/workflows/suite-integ-test-other.yml
    concurrency:
      group: CI-integ-test-other
      cancel-in-progress: false
    with:
      skip-dist: true
    secrets: inherit

  dependency-submission-integ-tests:
    permissions:
      contents: write
    needs: other-integ-tests
    uses: ./.github/workflows/suite-integ-test-dependency-submission.yml
    concurrency:
      group: CI-integ-test-dependency-submission
      cancel-in-progress: false
    with:
      skip-dist: true
    secrets: inherit
