name: suite-integ-test-caching

on:
  workflow_call:
    inputs:
      runner-os:
        type: string
        default: '["ubuntu-latest"]'
      skip-dist:
        type: boolean
        default: false

permissions:
  contents: read

jobs:
  cache-cleanup:
    uses: ./.github/workflows/integ-test-cache-cleanup.yml
    with:
      runner-os: '${{ inputs.runner-os }}'
      skip-dist: ${{ inputs.skip-dist }}

  caching-config:
    uses: ./.github/workflows/integ-test-caching-config.yml
    with:
      runner-os: '${{ inputs.runner-os }}'
      skip-dist: ${{ inputs.skip-dist }}

  restore-configuration-cache:
    if: ${{ ! github.event.pull_request.head.repo.fork }}
    uses: ./.github/workflows/integ-test-restore-configuration-cache.yml
    with:
      skip-dist: ${{ inputs.skip-dist }}
    secrets:
      GRADLE_ENCRYPTION_KEY: ${{ secrets.GRADLE_ENCRYPTION_KEY }}

  restore-containerized-gradle-home:
    uses: ./.github/workflows/integ-test-restore-containerized-gradle-home.yml
    with:
      skip-dist: ${{ inputs.skip-dist }}

  restore-custom-gradle-home:
    uses: ./.github/workflows/integ-test-restore-custom-gradle-home.yml
    with:
      skip-dist: ${{ inputs.skip-dist }}

  restore-gradle-home:
    uses: ./.github/workflows/integ-test-restore-gradle-home.yml
    with:
      skip-dist: ${{ inputs.skip-dist }}

  restore-java-toolchain:
    uses: ./.github/workflows/integ-test-restore-java-toolchain.yml
    with:
      skip-dist: ${{ inputs.skip-dist }}
